import { useEffect, useMemo, useRef, useState } from 'react';
import { useStudyData } from './hooks/useStudyData';
import './App.css';
import './product.css';

const dateKey = value => new Date(value).toISOString().slice(0, 10);
const today = () => new Date().toISOString().slice(0, 10);
const short = value => new Date(value + 'T00:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric' });

function Room({ running, notify }) { const [lamp, setLamp] = useState(true); return <section className={'scene ' + (running ? 'studying' : '') + (!lamp ? ' dim' : '')}><div className="room-window"><b>{running ? '✦' : '☀'}</b><i/><i/><i/></div><button className="room-lamp" onClick={() => { setLamp(v => !v); notify(lamp ? 'LAMP DIMMED.' : 'WARM LIGHTS ON.'); }} aria-label="Toggle desk lamp">◕</button><button className="room-books" onClick={() => notify('A GOOD BOOK MAKES A GREAT BREAK.')}>▰ ▰ ▰</button><button className="room-plant" onClick={() => notify('YOUR PLANT APPRECIATES THE COMPANY.')}>♣</button><div className="room-desk"><button onClick={() => notify('CAFFEINE PROTOCOL ACTIVATED. ☕')} aria-label="Coffee">☕</button><div className="student">{running ? '⌨' : '⌣'}</div><button onClick={() => notify('YOUR STUDY BUDDY BELIEVES IN YOU.')}>🐈</button><span>💻</span></div><div className="room-note">ONE STEP<br/>AT A TIME</div></section> }
function Modal({ title, children, close }) { return <div className="backdrop" role="presentation" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e => e.stopPropagation()}><button className="close" onClick={close} aria-label="Close">×</button><h2>{title}</h2>{children}</section></div> }

export default function App() {
 const store = useStudyData(), { data, update, addSubject, addQuest, saveQuest, completeQuest, addEvent, saveEvent, recordSession, stats } = store;
 const [tab, setTab] = useState('HOME'), [toast, setToast] = useState(''), [modal, setModal] = useState(null), [calendarDate, setCalendarDate] = useState(new Date()), [calendarView, setCalendarView] = useState('MONTH'), toastTimer = useRef();
 const [timer, setTimer] = useState({ running: false, mode: 'focus', seconds: 1500, subjectId: '', questId: '' });
 const notify = text => { setToast(text); clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 2400); };
 useEffect(() => { if (!timer.running) return; const tick = setInterval(() => setTimer(old => { if (old.seconds > 1) return { ...old, seconds: old.seconds - 1 }; if (old.mode === 'focus') { recordSession({ minutes: 25, subjectId: old.subjectId, questId: old.questId }); notify('FOCUS COMPLETE! +25 XP'); return { ...old, running: false, mode: 'break', seconds: 300 }; } notify('BREAK COMPLETE. READY TO FOCUS?'); return { ...old, running: false, mode: 'focus', seconds: 1500 }; }), 1000); return () => clearInterval(tick); }, [timer.running]);
 const nav = [['HOME','⌂'],['CALENDAR','▦'],['QUESTS','▤'],['TIMER','◉'],['SUBJECTS','▣'],['STATS','▥'],['ACHIEVEMENTS','♜'],['SETTINGS','⚙']];
 const plannedToday = data.events.filter(e => e.date === today()), upcoming = data.events.filter(e => e.date >= today()).sort((a,b) => (a.date + a.startTime).localeCompare(b.date + b.startTime)).slice(0,4);
 const subjectName = id => data.subjects.find(s => s.id === id)?.name || 'No subject';
 const form = e => { e.preventDefault(); const fields = Object.fromEntries(new FormData(e.currentTarget)); if (modal === 'subject') { addSubject({ name: fields.name, color: fields.color || '#8748fb' }); notify('SUBJECT CREATED!'); } if (modal === 'quest') { addQuest({ title: fields.title, subjectId: fields.subjectId, priority: fields.priority, dueDate: fields.dueDate, duration: Number(fields.duration || 0), notes: fields.notes }); notify('QUEST ADDED!'); } if (modal === 'event') { addEvent({ title: fields.title, date: fields.date, startTime: fields.startTime, endTime: fields.endTime, type: fields.type, subjectId: fields.subjectId, questId: fields.questId, description: fields.description }); notify('EVENT ADDED!'); } setModal(null); };
 const days = useMemo(() => { const start = new Date(calendarDate.getFullYear(), calendarDate.getMonth(), 1), offset = (start.getDay() + 6) % 7; return Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(i - offset + 1); return d; }); }, [calendarDate]);
 const renderModal = () => { if (!modal) return null; if (modal === 'subject') return <Modal title="ADD SUBJECT" close={() => setModal(null)}><form className="modal-form" onSubmit={form}><label>SUBJECT NAME<input required name="name" placeholder="e.g. Mathematics" autoFocus /></label><label>ACCENT COLOR<input name="color" type="color" defaultValue="#8748fb" /></label><button className="primary">CREATE SUBJECT</button></form></Modal>;
 if (modal === 'quest') return <Modal title="CREATE QUEST" close={() => setModal(null)}><form className="modal-form" onSubmit={form}><label>QUEST TITLE<input required name="title" placeholder="What needs doing?" autoFocus /></label><div className="form-row"><label>SUBJECT<select name="subjectId"><option value="">No subject</option>{data.subjects.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>PRIORITY<select name="priority"><option>Medium</option><option>High</option><option>Low</option></select></label></div><div className="form-row"><label>DUE DATE<input name="dueDate" type="date" /></label><label>EST. MINUTES<input name="duration" type="number" min="0" placeholder="30" /></label></div><label>NOTES<textarea name="notes" placeholder="Optional context or next step" /></label><button className="primary">ADD QUEST</button></form></Modal>;
 if (modal === 'event') return <Modal title="PLAN EVENT" close={() => setModal(null)}><form className="modal-form" onSubmit={form}><label>EVENT TITLE<input required name="title" placeholder="What is happening?" autoFocus /></label><div className="form-row"><label>DATE<input required name="date" type="date" defaultValue={today()} /></label><label>TYPE<select name="type"><option>Class</option><option>Deadline</option><option>Exam</option><option>Study session</option><option>Project</option><option>Personal</option><option>Reminder</option></select></label></div><div className="form-row"><label>START<input name="startTime" type="time" /></label><label>END<input name="endTime" type="time" /></label></div><label>SUBJECT<select name="subjectId"><option value="">No subject</option>{data.subjects.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>LINK QUEST<select name="questId"><option value="">No linked quest</option>{data.quests.map(q => <option value={q.id} key={q.id}>{q.title}</option>)}</select></label><label>DESCRIPTION<textarea name="description" placeholder="Optional details" /></label><button className="primary">ADD TO CALENDAR</button></form></Modal>;
 if (modal.type === 'quest') { const q = modal.item; return <Modal title="QUEST DETAILS" close={() => setModal(null)}><p className="detail-title">{q.title}</p><p>{q.notes || 'No notes added.'}</p><dl><dt>STATUS</dt><dd>{q.status}</dd><dt>SUBJECT</dt><dd>{subjectName(q.subjectId)}</dd><dt>DUE</dt><dd>{q.dueDate ? short(q.dueDate) : 'No due date'}</dd><dt>ESTIMATE</dt><dd>{q.duration || 0} minutes</dd></dl><button className="primary" onClick={() => { const completed = completeQuest(q.id); notify(completed ? 'QUEST COMPLETE! +10 XP' : 'QUEST REOPENED.'); setModal(null); }}>{q.status === 'complete' ? 'REOPEN QUEST' : 'MARK COMPLETE'}</button><button className="danger" onClick={() => { update('quests', list => list.filter(x => x.id !== q.id)); update('events', list => list.filter(x => x.questId !== q.id)); notify('QUEST DELETED.'); setModal(null); }}>DELETE QUEST</button></Modal>;}
 if (modal.type === 'event') { const e = modal.item; return <Modal title="EVENT DETAILS" close={() => setModal(null)}><p className="detail-title">{e.title}</p><p>{e.description || 'No description added.'}</p><dl><dt>WHEN</dt><dd>{short(e.date)} {e.startTime || ''}</dd><dt>TYPE</dt><dd>{e.type}</dd><dt>SUBJECT</dt><dd>{subjectName(e.subjectId)}</dd></dl><button className="danger" onClick={() => { update('events', list => list.filter(x => x.id !== e.id)); notify('EVENT DELETED.'); setModal(null); }}>DELETE EVENT</button></Modal>;}
 if (modal.type === 'subject') { const s = modal.item, linked = data.quests.filter(q => q.subjectId === s.id), minutes = data.sessions.filter(x => x.subjectId === s.id).reduce((sum, x) => sum + x.minutes, 0); return <Modal title="SUBJECT DETAILS" close={() => setModal(null)}><p className="detail-title">{s.name}</p><dl><dt>QUESTS</dt><dd>{linked.length}</dd><dt>COMPLETE</dt><dd>{linked.filter(q => q.status === 'complete').length}</dd><dt>STUDY TIME</dt><dd>{minutes} minutes</dd><dt>UPCOMING</dt><dd>{data.events.filter(e => e.subjectId === s.id && e.date >= today()).length} events</dd></dl><button className="danger" onClick={() => { update('subjects', list => list.filter(x => x.id !== s.id)); notify('SUBJECT REMOVED.'); setModal(null); }}>REMOVE SUBJECT</button></Modal>;}
 return null; };
 const greeting = new Date().getHours() < 12 ? 'GOOD MORNING' : new Date().getHours() < 18 ? 'GOOD AFTERNOON' : 'GOOD EVENING';
 return <div className={'app ' + data.theme}><aside><div className="brand">✦ STUDY<span>FLOW</span><small>PLAN · FOCUS · REVIEW</small></div><nav>{nav.map(([name,icon]) => <button className={tab === name ? 'active' : ''} onClick={() => setTab(name)} key={name}><b>{icon}</b>{name}</button>)}</nav><div className="level"><small>LEVEL {String(stats.level).padStart(2,'0')}</small><div className="mini-buddy">⌣</div><b>{stats.xp % 500} / 500 XP</b><i><em style={{ width: (stats.xp % 500) / 5 + '%' }} /></i></div></aside><main><header><div className="mobile">✦ STUDY<span>FLOW</span></div><div className="hello"><b>{greeting}, BUILDER! {data.theme === 'light' ? '☀' : '☾'}</b><span>{stats.remaining ? stats.remaining + ' quests are waiting for you.' : 'Your study world is ready when you are.'}</span></div><button className="theme" onClick={() => update('theme', data.theme === 'light' ? 'dark' : 'light')}>{data.theme === 'light' ? '☀ DAY' : '☾ NIGHT'}</button></header>
 <div className="screen">{tab === 'HOME' && <><Room running={timer.running} notify={notify}/><section className="intro"><label>DAILY BASECAMP</label><h1>YOUR DAY, <em>YOUR FLOW.</em></h1><p>Plan the next step, focus deeply, then watch your progress take shape.</p><div className="stats">{[[stats.remaining,'QUESTS LEFT','▤'],[stats.completed,'COMPLETED','✦'],[stats.todayMinutes + 'm','STUDIED TODAY','◷'],[upcoming.length,'UP NEXT','▦']].map(x => <article key={x[1]}><span>{x[2]}</span><b>{x[0]}</b><small>{x[1]}</small></article>)}</div></section><section className="quick"><button onClick={() => setModal('quest')}>＋ ADD QUEST</button><button onClick={() => setModal('event')}>＋ ADD EVENT</button><button onClick={() => setTab('TIMER')}>▶ START FOCUS</button><button onClick={() => setModal('subject')}>＋ ADD SUBJECT</button></section><section className="home-columns"><Panel title="TODAY'S QUESTS" action={() => setModal('quest')} actionLabel="+ CREATE">{data.quests.filter(q => !q.dueDate || q.dueDate === today()).length ? data.quests.filter(q => !q.dueDate || q.dueDate === today()).map(q => <QuestRow q={q} key={q.id} subjectName={subjectName} completeQuest={completeQuest} notify={notify} open={() => setModal({type:'quest',item:q})}/>) : <Empty text="YOUR QUEST BOARD IS EMPTY" sub="What are you planning to accomplish today?" action={() => setModal('quest')} label="+ CREATE QUEST"/>}</Panel><Panel title="UP NEXT" action={() => setTab('CALENDAR')} actionLabel="CALENDAR">{upcoming.length ? upcoming.map(e => <button className="next-event" key={e.id} onClick={() => setModal({type:'event',item:e})}><b>{e.startTime || 'ALL DAY'}</b><span>{e.title}<small>{short(e.date)} · {e.type}</small></span></button>) : <Empty text="NOTHING SCHEDULED YET" sub="Plan something on your calendar." action={() => setModal('event')} label="+ ADD EVENT"/>}</Panel><Panel title="RECENT ACTIVITY">{data.activity.length ? data.activity.slice(0,4).map(a => <p className="activity" key={a.id}>✦ {a.text}<small>{new Date(a.date).toLocaleDateString()}</small></p>) : <Empty text="YOUR ACTIVITY WILL APPEAR HERE." sub="Your productivity story starts with one action."/ >}</Panel></section></>}
 {tab === 'QUESTS' && <section className="page"><PageHeader title="QUEST BOARD" subtitle="Turn assignments into manageable next steps." action={() => setModal('quest')} label="+ CREATE QUEST"/><div className="filterbar"><span>{data.quests.length} total · {stats.completed} complete</span><select onChange={e => { const value=e.target.value; update('quests', list => [...list].sort((a,b) => value === 'due' ? (a.dueDate || '9999').localeCompare(b.dueDate || '9999') : a.title.localeCompare(b.title))); }}><option value="due">Sort by due date</option><option value="title">Sort by title</option></select></div><Panel title="ALL QUESTS">{data.quests.length ? data.quests.map(q => <QuestRow q={q} key={q.id} subjectName={subjectName} completeQuest={completeQuest} notify={notify} open={() => setModal({type:'quest',item:q})}/>) : <Empty text="NO QUESTS YET" sub="Ready to plan your first quest?" action={() => setModal('quest')} label="+ CREATE QUEST"/>}</Panel></section>}
 {tab === 'CALENDAR' && <Calendar date={calendarDate} setDate={setCalendarDate} days={days} events={data.events} view={calendarView} setView={setCalendarView} add={() => setModal('event')} open={event => setModal({type:'event',item:event})}/>}
 {tab === 'TIMER' && <Timer timer={timer} setTimer={setTimer} subjects={data.subjects} quests={data.quests} subjectName={subjectName} stats={stats}/>}
 {tab === 'SUBJECTS' && <section className="page"><PageHeader title="SUBJECT LIBRARY" subtitle="Organize your academic worlds." action={() => setModal('subject')} label="+ ADD SUBJECT"/><div className="subject-grid">{data.subjects.length ? data.subjects.map(s => <button className="subject-card" style={{'--subject':s.color || '#8748fb'}} key={s.id} onClick={() => setModal({type:'subject',item:s})}><b>{s.name}</b><span>{data.quests.filter(q => q.subjectId === s.id).filter(q => q.status === 'complete').length}/{data.quests.filter(q => q.subjectId === s.id).length} quests complete</span><small>{data.sessions.filter(x => x.subjectId === s.id).reduce((n,x) => n+x.minutes,0)} minutes studied</small></button>) : <Empty text="NO SUBJECTS YET" sub="Add your first subject to start organizing." action={() => setModal('subject')} label="+ ADD SUBJECT"/>}</div></section>}
 {tab === 'STATS' && <Stats stats={stats} sessions={data.sessions} quests={data.quests}/>}
 {tab === 'ACHIEVEMENTS' && <Achievements stats={stats}/>}
 {tab === 'SETTINGS' && <section className="page"><PageHeader title="SETTINGS" subtitle="Your local StudyFlow preferences."/><Panel title="DATA"><p className="settings-copy">All StudyFlow data stays in this browser using local storage.</p><button className="danger" onClick={() => { if (confirm('Clear all StudyFlow data? This cannot be undone.')) { localStorage.removeItem('studyflow-product-v2'); location.reload(); } }}>CLEAR ALL LOCAL DATA</button></Panel></section>}</div></main>{toast && <div className="toast">✦ {toast}</div>}{renderModal()}</div>;
}
function Panel({title,children,action,actionLabel}) { return <section className="panel"><h2>{title}{action && <button onClick={action}>{actionLabel}</button>}</h2>{children}</section> }
function Empty({text,sub,action,label}) { return <div className="empty"><b>{text}</b><span>{sub}</span>{action && <button onClick={action}>{label}</button>}</div> }
function PageHeader({title,subtitle,action,label}) { return <header className="page-header"><div><label>STUDYFLOW SYSTEM</label><h1>{title}</h1><p>{subtitle}</p></div>{action && <button className="primary" onClick={action}>{label}</button>}</header> }
function QuestRow({q,subjectName,completeQuest,notify,open}) { return <article className={'quest-row ' + q.status}><button className="check" onClick={() => { const next = completeQuest(q.id); notify(next ? 'QUEST COMPLETE! +10 XP' : 'QUEST REOPENED.'); }}>{q.status === 'complete' ? '✓' : ''}</button><button className="quest-title" onClick={open}>{q.title}<small>{subjectName(q.subjectId)} · {q.dueDate ? 'Due ' + short(q.dueDate) : 'No deadline'}</small></button><b>{q.priority || 'Medium'}</b></article> }
function Timer({timer,setTimer,subjects,quests,subjectName,stats}) { const reset = mode => setTimer({ ...timer, running:false, mode, seconds:mode === 'focus' ? 1500 : 300 }); const display = String(Math.floor(timer.seconds/60)).padStart(2,'0') + ':' + String(timer.seconds%60).padStart(2,'0'); return <section className="page timer-page"><PageHeader title="FOCUS STATION" subtitle="Choose what matters, then give it your full attention."/><section className={'timer-box ' + (timer.running ? 'running' : '')}><div className="tabs"><button className={timer.mode==='focus'?'on':''} onClick={() => reset('focus')}>FOCUS</button><button className={timer.mode==='break'?'on':''} onClick={() => reset('break')}>BREAK</button></div>{timer.mode==='focus' && <div className="timer-selects"><label>SUBJECT<select value={timer.subjectId} onChange={e => setTimer({...timer,subjectId:e.target.value})}><option value="">Select subject</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>QUEST <select value={timer.questId} onChange={e => setTimer({...timer,questId:e.target.value})}><option value="">Optional quest</option>{quests.filter(q => q.status !== 'complete').map(q => <option key={q.id} value={q.id}>{q.title}</option>)}</select></label></div>}<strong>{display}</strong><div className="pips">{Array.from({length:10},(_,i)=><i className={i<Math.ceil((1-timer.seconds/(timer.mode==='focus'?1500:300))*10)?'on':''} key={i}/>)}</div><div className="controls"><button className="primary" onClick={() => setTimer({...timer,running:!timer.running})}>{timer.running?'Ⅱ PAUSE':'▶ START'}</button><button onClick={() => reset(timer.mode)}>↻ RESET</button><button onClick={() => reset(timer.mode==='focus'?'break':'focus')}>» SKIP</button></div></section><div className="timer-summary"><b>{stats.sessions}</b> completed sessions · <b>{stats.todayMinutes}m</b> focused today · working on <b>{timer.subjectId ? subjectName(timer.subjectId) : 'your next goal'}</b></div></section> }
function Calendar({date,setDate,days,events,view,setView,add,open}) { const month = date.toLocaleDateString(undefined,{month:'long',year:'numeric'}); return <section className="page calendar"><PageHeader title="CALENDAR" subtitle="Plan classes, deadlines, and study time." action={add} label="+ ADD EVENT"/><div className="calendar-tools"><div><button onClick={() => setDate(new Date(date.getFullYear(),date.getMonth()-1,1))}>←</button><b>{month}</b><button onClick={() => setDate(new Date(date.getFullYear(),date.getMonth()+1,1))}>→</button><button onClick={() => setDate(new Date())}>TODAY</button></div><div className="tabs">{['MONTH','WEEK','DAY'].map(x => <button className={view===x?'on':''} onClick={() => setView(x)} key={x}>{x}</button>)}</div></div><div className={'calendar-grid '+view.toLowerCase()}>{['MON','TUE','WED','THU','FRI','SAT','SUN'].map(x => <b key={x}>{x}</b>)}{days.map(d => { const key=dateKey(d), items=events.filter(e => e.date===key); return <button className={'calendar-day '+(key===today()?'today':'')+(d.getMonth()!==date.getMonth()?' muted':'')} key={key} onClick={add}><span>{d.getDate()}</span>{items.slice(0,3).map(e => <i className={e.type.toLowerCase().replace(' ','-')} onClick={x => {x.stopPropagation();open(e)}} key={e.id}>{e.startTime ? e.startTime+' ' : ''}{e.title}</i>)}</button>})}</div></section> }
function Stats({stats,sessions,quests}) { return <section className="page"><PageHeader title="YOUR STATS" subtitle="Your real study story, built one session at a time."/><div className="stats big">{[[stats.todayMinutes+'m','TODAY'],[stats.weekMinutes+'m','THIS WEEK'],[stats.completed,'QUESTS COMPLETE'],[stats.sessions,'FOCUS SESSIONS']].map(x => <article key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></article>)}</div><div className="home-columns"><Panel title="COMPLETION RATE"><div className="meter"><i style={{width:stats.rate+'%'}}/></div><b>{stats.rate}% of your quests are complete.</b></Panel><Panel title="STREAK"><div className="empty"><b>{stats.streak ? '🔥 '+stats.streak+' DAY STREAK' : 'NO ACTIVE STREAK'}</b><span>Complete a quest or focus session today to build it.</span></div></Panel></div></section> }
function Achievements({stats}) { const list=[['FIRST QUEST',stats.completed>0,'Complete your first quest.'],['FIRST FOCUS',stats.sessions>0,'Finish a focus session.'],['CONSISTENT',stats.streak>=3,'Study for three consecutive days.'],['FOCUS MASTER',stats.sessions>=10,'Complete ten focus sessions.']]; return <section className="page"><PageHeader title="ACHIEVEMENTS" subtitle="Earned through real progress, never by opening the app."/><div className="achievement-grid">{list.map(x => <article className={x[1]?'unlocked':'locked'} key={x[0]}><b>{x[1]?'🏆':'🔒'} {x[0]}</b><span>{x[2]}</span><small>{x[1]?'UNLOCKED':'KEEP GOING'}</small></article>)}</div></section> }
