import { useEffect, useMemo, useRef, useState } from 'react';
import { useStudyFlow } from './context/useStudyFlow.js';
import characterIdle from './assets/characters/studyflow_character_idle.png';
import { sfx, setSound as setSfxSound, setAmbient } from './three/sfx.js';
import Px from './components/Px.jsx';
import { greeting, TIMER_DUR, TIMER_LABEL } from './utils/times.js';
import { unlockState } from './utils/achievements.js';
import './App.css';
import './product.css';
import './three/World.css';
import HomeDashboard from './components/home/HomeDashboard.jsx';

const dateKey = value => new Date(value).toISOString().slice(0, 10);
const today = () => new Date().toISOString().slice(0, 10);
const short = value => new Date(value + 'T00:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
function Modal({ title, children, close }) { return <div className="backdrop" role="presentation" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e => e.stopPropagation()}><button className="close" onClick={close} aria-label="Close">×</button><h2>{title}</h2>{children}</section></div> }

export default function App() {
 const store = useStudyFlow(), { data, update, addSubject, addQuest, addEvent, recordSession, addTask, saveTask, deleteTask, setProfile, stats } = store;
 const [tab, setTab] = useState('HOME'), [toast, setToast] = useState(''), [modal, setModal] = useState(null), [calendarDate, setCalendarDate] = useState(new Date()), [calendarView, setCalendarView] = useState('MONTH'), toastTimer = useRef();
 const [timer, setTimer] = useState({ running: false, mode: 'focus', seconds: TIMER_DUR.focus, subjectId: '', questId: '' });
 const notify = text => { setToast(text); clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 2400); };
 const [ux, setUx] = useState(() => { try { return { sound: true, ambient: false, ...JSON.parse(localStorage.getItem('studyflow-ux')) }; } catch { return { sound: true, ambient: false }; } });
 useEffect(() => localStorage.setItem('studyflow-ux', JSON.stringify(ux)), [ux]);
 const setUxKey = (k, v) => setUx(u => ({ ...u, [k]: v }));
 useEffect(() => { setSfxSound(ux.sound); }, [ux.sound]);
 useEffect(() => { setAmbient(ux.sound && ux.ambient); }, [ux.sound, ux.ambient]);
 const [nameDraft, setNameDraft] = useState(data.profile.name || 'SANDHYA');
 const completeQuest = id => { const done = store.completeQuest(id); if (done) sfx.unlock(); return done; };
 const toggleTaskSafe = id => { const done = store.toggleTask(id); if (done) sfx.unlock(); return done; };
 const lastLevel = useRef(stats.level);
 useEffect(() => { if (lastLevel.current && stats.level > lastLevel.current) sfx.levelup(); lastLevel.current = stats.level; }, [stats.level]);
 const timerRef = useRef(timer); const timerActions = useRef({}); useEffect(() => { timerRef.current = timer; timerActions.current = { recordSession, notify, sfx }; });
 useEffect(() => {
  if (!timer.running) return;
  const tick = setInterval(() => {
   const t = timerRef.current;
   if (t.seconds > 1) { setTimer(old => ({ ...old, seconds: old.seconds - 1 })); return; }
   const a = timerActions.current;
   if (t.mode === 'focus') { a.recordSession({ minutes: 25, subjectId: t.subjectId, questId: t.questId }); a.notify('FOCUS COMPLETE! +25 XP'); a.sfx.complete(); setTimer({ ...t, running: false, mode: 'short', seconds: TIMER_DUR.short }); }
   else { a.notify(t.mode === 'long' ? 'LONG BREAK COMPLETE. READY TO FOCUS?' : 'SHORT BREAK COMPLETE. READY TO FOCUS?'); a.sfx.click(); setTimer({ ...t, running: false, mode: 'focus', seconds: TIMER_DUR.focus }); }
  }, 1000); return () => clearInterval(tick);
 }, [timer.running]);
 const nav = [['HOME','home'],['CALENDAR','calendar'],['QUESTS','quest'],['TIMER','timer'],['SUBJECTS','subjects'],['STATS','stats'],['ACHIEVEMENTS','trophy'],['SETTINGS','gear']];
 const subjectName = id => data.subjects.find(s => s.id === id)?.name || 'No subject';
 const form = e => { e.preventDefault(); const fields = Object.fromEntries(new FormData(e.currentTarget)); if (modal === 'subject') { addSubject({ name: fields.name, color: fields.color || '#8748fb' }); notify('SUBJECT CREATED!'); } if (modal === 'quest') { addQuest({ title: fields.title, subjectId: fields.subjectId, priority: fields.priority, dueDate: fields.dueDate, duration: Number(fields.duration || 0), notes: fields.notes, track: fields.track || 'checklist', target: Number(fields.target) || 1 }); notify('QUEST ADDED!'); } if (modal === 'event' || (modal && modal.type === 'event' && !modal.item)) { addEvent({ title: fields.title, date: fields.date, startTime: fields.startTime, endTime: fields.endTime, type: fields.type, subjectId: fields.subjectId, questId: fields.questId, description: fields.description }); notify('EVENT ADDED!'); } if (modal === 'task') { addTask({ title: fields.title, description: fields.description, subjectId: fields.subjectId, date: fields.date, time: fields.time, priority: fields.priority }); notify('TASK ADDED!'); } setModal(null); };
 const days = useMemo(() => { const start = new Date(calendarDate.getFullYear(), calendarDate.getMonth(), 1), offset = (start.getDay() + 6) % 7; return Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(i - offset + 1); return d; }); }, [calendarDate]);
 const renderModal = () => { if (!modal) return null; if (modal === 'subject') return <Modal title="ADD SUBJECT" close={() => setModal(null)}><form className="modal-form" onSubmit={form}><label>SUBJECT NAME<input required name="name" placeholder="e.g. Mathematics" autoFocus /></label><label>ACCENT COLOR<input name="color" type="color" defaultValue="#8748fb" /></label><button className="primary">CREATE SUBJECT</button></form></Modal>;
 if (modal === 'quest') return <Modal title="CREATE QUEST" close={() => setModal(null)}><form className="modal-form" onSubmit={form}><label>QUEST TITLE<input required name="title" placeholder="What needs doing?" autoFocus /></label><div className="form-row"><label>SUBJECT<select name="subjectId"><option value="">No subject</option>{data.subjects.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>PRIORITY<select name="priority"><option>Medium</option><option>High</option><option>Low</option></select></label></div><div className="form-row"><label>PROGRESS TRACK<select name="track"><option value="checklist">Checklist</option><option value="tasks">Tasks by subject</option><option value="sessions">Focus sessions</option><option value="streak">Streak days</option></select></label><label>TARGET VALUE<input name="target" type="number" min="1" placeholder="1" /></label></div><div className="form-row"><label>DUE DATE<input name="dueDate" type="date" /></label><label>EST. MINUTES<input name="duration" type="number" min="0" placeholder="30" /></label></div><label>NOTES<textarea name="notes" placeholder="Optional context or next step" /></label><button className="primary">ADD QUEST</button></form></Modal>;
 if (modal === 'task') return <Modal title="ADD TASK" close={() => setModal(null)}><form className="modal-form" onSubmit={form}><label>TASK TITLE<input required name="title" placeholder="What will you do today?" autoFocus /></label><label>DESCRIPTION<textarea name="description" placeholder="Optional details" /></label><div className="form-row"><label>SUBJECT<select name="subjectId"><option value="">No subject</option>{data.subjects.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>PRIORITY<select name="priority"><option>Medium</option><option>High</option><option>Low</option></select></label></div><div className="form-row"><label>DATE<input name="date" type="date" defaultValue={today()} /></label><label>TIME<input name="time" type="time" /></label></div><button className="primary">ADD TASK</button></form></Modal>;
 if (modal === 'event' || (modal && modal.type === 'event' && !modal.item)) return <Modal title="PLAN EVENT" close={() => setModal(null)}><form className="modal-form" onSubmit={form}><label>EVENT TITLE<input required name="title" placeholder="What is happening?" autoFocus /></label><div className="form-row"><label>DATE<input required name="date" type="date" defaultValue={modal.date || today()} /></label><label>TYPE<select name="type"><option>Class</option><option>Deadline</option><option>Exam</option><option>Study session</option><option>Project</option><option>Personal</option><option>Reminder</option></select></label></div><div className="form-row"><label>START<input name="startTime" type="time" /></label><label>END<input name="endTime" type="time" /></label></div><label>SUBJECT<select name="subjectId"><option value="">No subject</option>{data.subjects.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>LINK QUEST<select name="questId"><option value="">No linked quest</option>{data.quests.map(q => <option value={q.id} key={q.id}>{q.title}</option>)}</select></label><label>DESCRIPTION<textarea name="description" placeholder="Optional details" /></label><button className="primary">ADD TO CALENDAR</button></form></Modal>;
 if (modal.type === 'quest') { const q = modal.item; return <Modal title="QUEST DETAILS" close={() => setModal(null)}><p className="detail-title">{q.title}</p><p>{q.notes || 'No notes added.'}</p><dl><dt>STATUS</dt><dd>{q.status}</dd><dt>SUBJECT</dt><dd>{subjectName(q.subjectId)}</dd><dt>DUE</dt><dd>{q.dueDate ? short(q.dueDate) : 'No due date'}</dd><dt>ESTIMATE</dt><dd>{q.duration || 0} minutes</dd></dl><button className="primary" onClick={() => { const completed = completeQuest(q.id); notify(completed ? 'QUEST COMPLETE! +10 XP' : 'QUEST REOPENED.'); setModal(null); }}>{q.status === 'complete' ? 'REOPEN QUEST' : 'MARK COMPLETE'}</button><button className="danger" onClick={() => { update('quests', list => list.filter(x => x.id !== q.id)); update('events', list => list.filter(x => x.questId !== q.id)); notify('QUEST DELETED.'); setModal(null); }}>DELETE QUEST</button></Modal>;}
 if (modal.type === 'task') { const t = modal.item; return <Modal title="TASK DETAILS" close={() => setModal(null)}><form className="modal-form" onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); saveTask(t.id, { title: f.title, description: f.description, subjectId: f.subjectId, date: f.date, time: f.time, priority: f.priority }); notify('TASK UPDATED.'); setModal(null); }}><label>TASK TITLE<input name="title" required defaultValue={t.title} /></label><label>DESCRIPTION<textarea name="description" defaultValue={t.description || ''} /></label><div className="form-row"><label>SUBJECT<select name="subjectId" defaultValue={t.subjectId || ''}><option value="">No subject</option>{data.subjects.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>PRIORITY<select name="priority" defaultValue={t.priority || 'Medium'}><option>High</option><option>Medium</option><option>Low</option></select></label></div><div className="form-row"><label>DATE<input name="date" type="date" defaultValue={t.date} /></label><label>TIME<input name="time" type="time" defaultValue={t.time || ''} /></label></div><div className="form-row"><button className="primary">SAVE TASK</button><button className={t.completed ? '' : 'primary'} type="button" onClick={() => { const done = toggleTaskSafe(t.id); notify(done ? 'TASK COMPLETE! +' + (t.xpReward || 0) + ' XP' : 'TASK REOPENED.'); setModal({ type: 'task', item: { ...t, completed: done } }); }}>{t.completed ? '↻ REOPEN' : '✓ MARK COMPLETE'}</button></div><button className="danger" type="button" onClick={() => { deleteTask(t.id); notify('TASK DELETED.'); setModal(null); }}>DELETE TASK</button></form></Modal>;}
 if (modal.type === 'event' && modal.item) { const e = modal.item; return <Modal title="EVENT DETAILS" close={() => setModal(null)}><p className="detail-title">{e.title}</p><p>{e.description || 'No description added.'}</p><dl><dt>WHEN</dt><dd>{short(e.date)} {e.startTime || ''}</dd><dt>TYPE</dt><dd>{e.type}</dd><dt>SUBJECT</dt><dd>{subjectName(e.subjectId)}</dd></dl><button className="danger" onClick={() => { update('events', list => list.filter(x => x.id !== e.id)); notify('EVENT DELETED.'); setModal(null); }}>DELETE EVENT</button></Modal>;}
 if (modal.type === 'subject') { const s = modal.item, linked = data.quests.filter(q => q.subjectId === s.id), minutes = data.sessions.filter(x => x.subjectId === s.id).reduce((sum, x) => sum + x.minutes, 0); return <Modal title="SUBJECT DETAILS" close={() => setModal(null)}><p className="detail-title">{s.name}</p><dl><dt>QUESTS</dt><dd>{linked.length}</dd><dt>COMPLETE</dt><dd>{linked.filter(q => q.status === 'complete').length}</dd><dt>STUDY TIME</dt><dd>{minutes} minutes</dd><dt>UPCOMING</dt><dd>{data.events.filter(e => e.subjectId === s.id && e.date >= today()).length} events</dd></dl><button className="danger" onClick={() => { update('subjects', list => list.filter(x => x.id !== s.id)); notify('SUBJECT REMOVED.'); setModal(null); }}>REMOVE SUBJECT</button></Modal>;}
 return null; };
 return <div className={'app ' + data.theme}><aside><div className="brand"><Px n="star" s={26}/> STUDY<span>FLOW</span><small>PLAN · FOCUS · REVIEW</small></div><nav>{nav.map(([name,icon]) => <button className={tab === name ? 'active' : ''} onClick={() => setTab(name)} key={name}><b><Px n={icon} s={21}/></b>{name}</button>)}</nav><div className="profile-card"><div className="avatar"><img src={characterIdle} alt="buddy"/></div><div className="p-info"><b className="p-level">LEVEL <em>{String(stats.level).padStart(2,'0')}</em></b><span className="p-xp">{stats.xp.toLocaleString()} XP</span><div className="p-bar"><i style={{ width: stats.levelProgress + '%' }} /></div></div></div></aside><main><header><div className="mobile"><Px n="star" s={18}/> STUDY<span>FLOW</span></div><div className="h-left"><div className="h-big"><Px n="star" s={20}/> <b>{greeting()}, {(data.profile.name || 'SANDHYA').toUpperCase()}{data.profile.name ? '!' : ''} <Px n={data.theme === 'light' ? 'sun' : 'moon'} s={16}/></b></div><span className="h-sub">Keep going, you've got this! · {stats.remaining ? stats.remaining + ' quests waiting.' : 'Your study world is ready when you are.'}</span></div><div className="h-right"><div className="h-chip xp"><Px n="star" s={14}/> {stats.xp} XP</div><div className="h-chip flame"><Px n="flame" s={14}/> {stats.streak}</div><button className="h-icon h-bell" aria-label="Notifications"><Px n="bell" s={16}/></button><button className="h-icon" onClick={() => update('theme', data.theme === 'light' ? 'dark' : 'light')} aria-label="Toggle theme"><Px n={data.theme === 'light' ? 'sun' : 'moon'} s={16}/></button><span className="h-avatar"><img src={characterIdle} alt="buddy"/></span></div></header>
 <div className="screen">{tab !== 'HOME' && <div className="vignette" aria-hidden="true"/>}{tab === 'HOME' && <HomeDashboard timer={timer} setTimer={setTimer} calendarDate={calendarDate} setCalendarDate={setCalendarDate} setTab={setTab} notify={notify} toggleTask={toggleTaskSafe} openQuest={q => setModal({ type: 'quest', item: q })} openTask={t => setModal({ type: 'task', item: t })} openEvent={e => setModal({ type: 'event', item: e })} openAddTask={() => setModal('task')} openAddEvent={date => setModal({ type: 'event', date })} onAddQuest={() => setModal('quest')} />}
 {tab === 'QUESTS' && <section className="page"><PageHeader title="QUEST BOARD" subtitle="Turn assignments into manageable next steps." action={() => setModal('quest')} label="+ CREATE QUEST"/><div className="filterbar"><span>{data.quests.length} quests · {data.tasks.length} tasks</span><select onChange={e => { const value=e.target.value; update('quests', list => [...list].sort((a,b) => value === 'due' ? (a.dueDate || '9999').localeCompare(b.dueDate || '9999') : a.title.localeCompare(b.title))); }}><option value="due">Sort by due date</option><option value="title">Sort by title</option></select><button className="dashed-add" onClick={() => setModal('task')}>+ ADD TASK</button></div><Panel title={'ALL TASKS · ' + stats.tasksTodayDone + ' / ' + stats.tasksToday + ' today'}>{data.tasks.length ? data.tasks.sort((a,b) => (a.date || '').localeCompare(b.date || '')).map(t => <article className={'quest-row' + (t.completed ? ' complete' : '')} key={t.id}><button className="check" onClick={() => { const next = toggleTaskSafe(t.id); notify(next ? 'TASK COMPLETE! +' + (t.xpReward || 0) + ' XP' : 'TASK REOPENED.'); }}>{t.completed ? '✓' : ''}</button><button className="quest-title" onClick={() => setModal({ type: 'task', item: t })}>{t.title}<small>{subjectName(t.subjectId)} · {short(t.date)}{t.time ? ' · ' + t.time : ''}</small></button><b>{t.priority}</b></article>) : <Empty text="NO TASKS YET" sub="Plan your first task from the home dashboard." action={() => setModal('task')} label="+ ADD TASK"/>}</Panel><Panel title="ALL QUESTS">{data.quests.length ? data.quests.map(q => <QuestRow q={q} key={q.id} subjectName={subjectName} completeQuest={completeQuest} notify={notify} open={() => setModal({type:'quest',item:q})}/>) : <Empty text="NO QUESTS YET" sub="Ready to plan your first quest?" action={() => setModal('quest')} label="+ CREATE QUEST"/>}</Panel></section>}
 {tab === 'CALENDAR' && <Calendar date={calendarDate} setDate={setCalendarDate} days={days} events={data.events} view={calendarView} setView={setCalendarView} add={() => setModal('event')} open={event => setModal({type:'event',item:event})}/>}
 {tab === 'TIMER' && <Timer timer={timer} setTimer={setTimer} subjects={data.subjects} quests={data.quests} stats={stats}/>}
 {tab === 'SUBJECTS' && <section className="page"><PageHeader title="SUBJECT LIBRARY" subtitle="Organize your academic worlds." action={() => setModal('subject')} label="+ ADD SUBJECT"/><div className="subject-grid">{data.subjects.length ? data.subjects.map(s => <button className="subject-card" style={{'--subject':s.color || '#8748fb'}} key={s.id} onClick={() => setModal({type:'subject',item:s})}><b>{s.name}</b><span>{data.quests.filter(q => q.subjectId === s.id).filter(q => q.status === 'complete').length}/{data.quests.filter(q => q.subjectId === s.id).length} quests complete</span><small>{data.sessions.filter(x => x.subjectId === s.id).reduce((n,x) => n+x.minutes,0)} minutes studied</small></button>) : <Empty text="NO SUBJECTS YET" sub="Add your first subject to start organizing." action={() => setModal('subject')} label="+ ADD SUBJECT"/>}</div></section>}
 {tab === 'STATS' && <Stats stats={stats} sessions={data.sessions} quests={data.quests}/>}
 {tab === 'ACHIEVEMENTS' && <Achievements stats={stats}/>}
 {tab === 'SETTINGS' && <section className="page"><PageHeader title="SETTINGS" subtitle="Tune your StudyFlow experience."/><Panel title="PROFILE"><div className="setting-row"><span><b>PLAYER NAME</b><span>Shown in your greeting.</span></span><input className="name-input" value={nameDraft} onChange={e => setNameDraft(e.target.value)} aria-label="Player name"/></div><button className="primary" onClick={() => { setProfile({ name: nameDraft.trim() || 'SANDHYA' }); notify('PROFILE SAVED.'); }}>SAVE NAME</button></Panel><Panel title="EXPERIENCE"><div className="setting-row"><span><b>SOUND</b><span>Interface chimes and prop sounds.</span></span><button className={ux.sound ? 'on' : ''} onClick={() => { setUxKey('sound', !ux.sound); sfx.click(); }}>{ux.sound ? 'ON' : 'OFF'}</button></div><div className="setting-row"><span><b>AMBIENT TONE</b><span>A soft lo-fi room tone in the background.</span></span><button className={ux.ambient ? 'on' : ''} onClick={() => { setUxKey('ambient', !ux.ambient); sfx.click(); }}>{ux.ambient ? 'ON' : 'OFF'}</button></div></Panel><Panel title="DATA"><p className="settings-copy">All StudyFlow data stays in this browser using local storage.</p><button className="danger" onClick={() => { if (confirm('Clear all StudyFlow data? This cannot be undone.')) { localStorage.removeItem('studyflow-product-v2'); location.reload(); } }}>CLEAR ALL LOCAL DATA</button></Panel></section>}</div></main>{toast && <div className="toast"><Px n="star" s={14}/> {toast}</div>}{renderModal()}</div>;
}
function Panel({title,children,action,actionLabel}) { return <section className="panel"><h2>{title}{action && <button onClick={action}>{actionLabel}</button>}</h2>{children}</section> }
function Empty({text,sub,action,label}) { return <div className="empty"><b>{text}</b><span>{sub}</span>{action && <button onClick={action}>{label}</button>}</div> }
function PageHeader({title,subtitle,action,label}) { return <header className="page-header"><div><label>STUDYFLOW SYSTEM</label><h1>{title}</h1><p>{subtitle}</p></div>{action && <button className="primary" onClick={action}>{label}</button>}</header> }
function QuestRow({q,subjectName,completeQuest,notify,open}) { return <article className={'quest-row ' + q.status}><button className="check" onClick={() => { const next = completeQuest(q.id); notify(next ? 'QUEST COMPLETE! +10 XP' : 'QUEST REOPENED.'); }}>{q.status === 'complete' ? '✓' : ''}</button><button className="quest-title" onClick={open}>{q.title}<small>{subjectName(q.subjectId)} · {q.dueDate ? 'Due ' + short(q.dueDate) : 'No deadline'}</small></button><b>{q.priority || 'Medium'}</b></article> }
function Timer({timer,setTimer,subjects,quests,stats}) { const reset = mode => setTimer({ ...timer, running:false, mode, seconds:TIMER_DUR[mode] }); const display = String(Math.floor(timer.seconds/60)).padStart(2,'0') + ':' + String(timer.seconds%60).padStart(2,'0'); const full = TIMER_DUR[timer.mode] || TIMER_DUR.focus; return <section className="page timer-page"><PageHeader title="FOCUS STATION" subtitle="Choose what matters, then give it your full attention."/><section className={'timer-box ' + (timer.running ? 'running' : '')}><div className="tabs">{['focus','short','long'].map(m => <button className={timer.mode===m?'on':''} key={m} onClick={() => { reset(m); sfx.click(); }}>{TIMER_LABEL[m]}</button>)}</div>{timer.mode==='focus' && <div className="timer-selects"><label>SUBJECT<select value={timer.subjectId} onChange={e => setTimer({...timer,subjectId:e.target.value})}><option value="">Select subject</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>QUEST <select value={timer.questId} onChange={e => setTimer({...timer,questId:e.target.value})}><option value="">Optional quest</option>{quests.filter(q => q.status !== 'complete').map(q => <option key={q.id} value={q.id}>{q.title}</option>)}</select></label></div>}<strong>{display}</strong><div className="pips">{Array.from({length:10},(_,i)=><i className={i<Math.ceil((1-timer.seconds/full)*10)?'on':''} key={i}/>)}</div><div className="controls"><button className="primary" onClick={() => { timer.running ? sfx.pause() : sfx.start(); setTimer({...timer,running:!timer.running}); }}>{timer.running?'Ⅱ PAUSE':'▶ START'}</button><button onClick={() => { reset(timer.mode); sfx.reset(); }}>↻ RESET</button><button onClick={() => { reset(timer.mode==='focus'?'short':'focus'); sfx.click(); }}>» SKIP</button></div></section><div className="timer-summary"><b>{stats.sessions}</b> completed sessions · <b>{stats.todayMinutes}m</b> today</div></section> }
function Calendar({date,setDate,days,events,view,setView,add,open}) { const month = date.toLocaleDateString(undefined,{month:'long',year:'numeric'}); return <section className="page calendar"><PageHeader title="CALENDAR" subtitle="Plan classes, deadlines, and study time." action={add} label="+ ADD EVENT"/><div className="calendar-tools"><div><button onClick={() => setDate(new Date(date.getFullYear(),date.getMonth()-1,1))}>←</button><b>{month}</b><button onClick={() => setDate(new Date(date.getFullYear(),date.getMonth()+1,1))}>→</button><button onClick={() => setDate(new Date())}>TODAY</button></div><div className="tabs">{['MONTH','WEEK','DAY'].map(x => <button className={view===x?'on':''} onClick={() => setView(x)} key={x}>{x}</button>)}</div></div><div className={'calendar-grid '+view.toLowerCase()}>{['MON','TUE','WED','THU','FRI','SAT','SUN'].map(x => <b key={x}>{x}</b>)}{days.map(d => { const key=dateKey(d), items=events.filter(e => e.date===key); return <button className={'calendar-day '+(key===today()?'today':'')+(d.getMonth()!==date.getMonth()?' muted':'')} key={key} onClick={add}><span>{d.getDate()}</span>{items.slice(0,3).map(e => <i className={e.type.toLowerCase().replace(' ','-')} onClick={x => {x.stopPropagation();open(e)}} key={e.id}>{e.startTime ? e.startTime+' ' : ''}{e.title}</i>)}</button>})}</div></section> }
function Stats({stats}) { return <section className="page"><PageHeader title="YOUR STATS" subtitle="Your real study story, built one session at a time."/><div className="stats big">{[[stats.todayMinutes+'m','TODAY'],[stats.weekMinutes+'m','THIS WEEK'],[stats.completed,'QUESTS COMPLETE'],[stats.sessions,'FOCUS SESSIONS']].map(x => <article key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></article>)}</div><div className="home-columns"><Panel title="COMPLETION RATE"><div className="meter"><i style={{width:stats.rate+'%'}}/></div><b>{stats.rate}% of your quests are complete.</b></Panel><Panel title="TASKS"><div className="meter"><i style={{width: stats.tasksToday ? Math.round(stats.tasksTodayDone/stats.tasksToday*100)+'%' : '0%'}}/></div><b>{stats.tasksTodayDone} of {stats.tasksToday} tasks done today.</b></Panel><Panel title="STREAK"><div className="empty"><b>{stats.streak ? <><Px n="flame" s={18}/> {stats.streak} DAY STREAK</> : 'NO ACTIVE STREAK'}</b><span>Complete a task or focus session today to build it.</span></div></Panel></div></section> }
function Achievements({stats}) { const list = unlockState(stats); return <section className="page"><PageHeader title="ACHIEVEMENTS" subtitle="Earned through real progress, never by opening the app."/><div className="achievement-grid">{list.map(a => <article className={a.unlocked?'unlocked':'locked'} key={a.title}><b>{a.unlocked?<Px n="trophy" s={20}/>:<Px n="lock" s={20}/>} {a.title}</b><span>{a.desc}</span><small>{a.unlocked?'UNLOCKED':'KEEP GOING'}</small></article>)}</div></section> }